coverage:
  range: 50..80
  round: down
  precision: 2

  status:
    project:
      default:
        target: 70%
        threshold: 1%
        if_ci_failed: error

    patch:
      default:
        target: 70%
        threshold: 1%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "**/*.spec.ts"
  - "**/*.test.ts"
  - "**/node_modules/**"
  - "**/coverage/**"
  - "**/dist/**"
  - "setup-jest.ts"
  - "jest.config.js"
  - "**/*.config.js"
  - "**/*.config.ts"
